---
title: "Untitled"
author: "Vamsi"
date: "11/4/2019"
output: pdf_document
---

```{r}
library(lpSolveAPI)
emax <- read.lp("emax.lp")
emax

solve(emax)
get.objective(emax)
get.constraints(emax)
get.variables(emax)

```
          z    x1          x2      x3     y1m          y1p   y2m
          
Applying the simplex method to this formulation yields an optimal solution of y1m = 0, y1p = 0, y2m = 8.33,  x1 = 8.33, x2 = 0, x3 = 0,This implies that y1 = 0 , so the first  goals are fully satisfied

```{r}

emax1 <- read.lp("emax _firststage.lp")
emax1

solve(emax1)
get.objective(emax1)
get.constraints(emax1)
get.variables(emax1)
```

The solution is Z = 0, with x1 = 9.375, and y1p = 6.25. As we have an optimal solution, 

```{r}

emax2 <- read.lp("emax _secondstage.lp")
emax2

solve(emax2)
get.objective(emax2)
get.constraints(emax2)
get.variables(emax2)
```

The solution is Z = 0, with x1 = 9.375, and y1p = 6.25. As we have an optimal solution,
```{r}

emax3 <- read.lp("emax _streamline.lp")
emax3

solve(emax3)
get.objective(emax3)
get.constraints(emax3)
get.variables(emax3)
```

